import os
import openpyxl

def write_list_to_file(file_path, str_list):
    with open(file_path, "w") as f:
        for item in str_list:
            splits = item.split("?")
            line1 = "mvn clean test '-Dtest=" + splits[0] + "#" + splits[1] + "' > TEMPORARY PATH TO SAVE THE LOG FILE"
            line2 = "java collect " + splits[0] + " " + splits[1]
            f.write("%s\n" % line1)
            f.write("%s\n" % line2)

if __name__ == '__main__':
    version = 1
    while version < 601:
        file_names = []
        workbook = openpyxl.load_workbook("TEST RESULT FILE GENERATED BY SurefireReportReader.java FOR EACH FAULTY VERSION")
        worksheet = workbook.active
        for row in worksheet.iter_rows():
            faulty = int(row[2].value)
            if faulty == 0:
                continue
            packagename = row[0].value
            filename = packagename.split(".")[-1] + "?" + row[1].value
            file_names.append(filename)
        file_path = "FILE PATH TO SAVE THE COMMAND FOR EACH FAULTY VERSION"
        write_list_to_file(file_path, file_names)
        version += 1
